services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: plannerpw
      POSTGRES_DB: plannerdb
    ports:
      - "4002:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: postgresql://planner:plannerpw@db:5432/plannerdb
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3333 
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pg_data: